version: "3.8"

services:
  neo4j:
    image: neo4j:2025.04.0          # current 2025.x community tag
    container_name: neo4j
    restart: unless-stopped

    environment:
      NEO4J_AUTH: neo4j/strongpassword123        # <user>/<password>
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G

    ports:
      - "7474:7474"   # HTTP + Neo4j Browser
      - "7687:7687"   # Bolt driver port

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./import:/import
      - ./plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs: